[package]
name = "vm_tut"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
console = "0.15.8"
libc = "0.2.155"
nix = { version = "0.29.0", features = ["poll"] }
signal-hook = "0.3.17"
termios = "0.3.3"

[profile.dev]
overflow-checks = false
